In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
vector  = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [5]:
q1 = torch.tensor([[1,2,3] , [4,5,6] , [7,8,9]])
q1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
q2 = torch.tensor([[9,8,7] ,[6,5,4] , [3,2,1]])
q2

tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

In [7]:
summ =q1 + q2
summ

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

In [8]:
diff  = q2  -q1
diff

tensor([[ 8,  6,  4],
        [ 2,  0, -2],
        [-4, -6, -8]])

In [9]:
normal_multi = q1* q2
normal_multi 

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])

In [11]:
matrix_multi = torch.matmul(q1 , q2)
matrix_multi 

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [18]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is used for the making of large dataset")
else:
    devic  = torch.device("CPU")
    print("Cpu is use for the making of large dataset")

device

GPU is used for the making of large dataset


device(type='cuda')

In [19]:
customer_data = torch.rand(1_000_000 ,3, device = device)
customer_data[:5]

tensor([[0.4935, 0.3072, 0.8965],
        [0.5759, 0.9914, 0.4891],
        [0.9893, 0.4253, 0.4459],
        [0.9873, 0.0164, 0.5730],
        [0.6531, 0.0765, 0.8373]], device='cuda:0')

In [20]:
customer_data[:8 , 1]

tensor([0.3072, 0.9914, 0.4253, 0.0164, 0.0765, 0.1453, 0.6614, 0.7942],
       device='cuda:0')